version: "3.9"

networks:
  management-network:
    driver: bridge

services:
  management-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - management-network